module.exports = function (title) {
	return title
		.replace('shell', 'Shell')
		.replace('wheelman', 'Wheelman')
		.replace('never dies', 'Never Dies')
		.replace('Saga Frontier', 'SaGa Frontier')
		.replace('Defcon 5 - Piece Has a Price', 'Defcon 5 - Peace Has a Price')
		.replace('Arc the Lad Collection (USA) (Disc 1 of 6)', 'Arc the Lad Collection: Arc the Lad (USA)')
		.replace('Arc the Lad Collection (USA) (Disc 2 of 6)', 'Arc the Lad Collection: Arc the Lad II (USA)')
		.replace('Arc the Lad Collection (USA) (Disc 3 of 6)', 'Arc the Lad Collection: Arc the Lad III (USA) (Disc 1 of 2)')
		.replace('Arc the Lad Collection (USA) (Disc 4 of 6)', 'Arc the Lad Collection: Arc the Lad III (USA) (Disc 2 of 2)')
		.replace('Arc the Lad Collection (USA) (Disc 5 of 6)', 'Arc the Lad Collection: Arc Arena: Monster Tournament (USA)')
		.replace('Arc the Lad Collection (USA) (Disc 6 of 6)', 'Arc the Lad Collection: The Making of Arc the Lad (USA)')
		.replace('Capcom Generations (Europe) (Disc 1 of 4)', 'Capcom Generations - Wings of Destiny (Europe) (Disc 1)')
		.replace('Capcom Generations (Europe) (Disc 2 of 4)', 'Capcom Generations - Chronicles of Arthur (Europe) (Disc 2)')
		.replace('Capcom Generations (Europe) (Disc 3 of 4)', 'Capcom Generations - The First Generation (Europe) (Disc 3)')
		.replace('Capcom Generations (Europe) (Disc 4 of 4)', 'Capcom Generations - Blazing Guns (Europe) (Disc 4)')
		.replace('Gran Turismo 2 - The Real Driving Simulator (USA) (Disc 1 of 3)', 'Gran Turismo 2 - Arcade Mode (USA)')
		.replace('Gran Turismo 2 - The Real Driving Simulator (USA) (Disc 2 of 3)', 'Gran Turismo 2 - Simulation Mode (USA)')
		.replace('Gran Turismo 2 - The Real Driving Simulator (USA) (Disc 3 of 3)', 'Gran Turismo 2: Music at the Speed of Sound: The Album (USA) (Bonus PlayStation Disc)')
		.replace('Grand Theft Auto [Director's Cut] (USA) (Disc 1 of 2)', 'Grand Theft Auto (USA)')
		.replace('Grand Theft Auto [Director's Cut] (USA) (Disc 2 of 2)', 'Grand Theft Auto: Mission Pack #1: London 1969 (USA)')
		.replace('Dino Crisis (USA) (Disc 1 of 2)', 'Dino Crisis (USA)')
		.replace('Dino Crisis (USA) (Disc 2 of 2)', 'Resident Evil 3: Nemesis (USA) (Demo Disk)')
}